### ISSUE TITLE
Fix text alignment for blog posts

### ISSUE THREAD

**Issue by vipul-sharma20** [Vernacular-ai/tech#14]
Center align the text. Currently it looks like below after removing the social media sharing options in 37f505c3ee2b4188b478469aa52f163738a9f250. Should be more left to be center aligned.

![image](https://i.imgur.com/m1B5G90.png)

---

Originally, it looked like below with the sticky social media sharing options

![image](https://i.imgur.com/AmGI1NP.png)

**Comment by lepisma** [comment]
Yea, I kept the grid blocks the same. Can remove the social media grid.

**Comment by vipul-sharma20** [comment]
![image](https://i.imgur.com/2PTIjjZ.png)

**Comment by vipul-sharma20** [comment]
![image](https://i.imgur.com/JdiBnnw.png)
