### ISSUE TITLE
Add a better code snippet formatting plugin

### ISSUE THREAD

**Issue by vipul-sharma20** [Vernacular-ai/tech#4]

**Comment by vipul-sharma20** [comment]
Suggested reference: https://docs.racket-lang.org/continue/

**Comment by lepisma** [comment]
current view -> 
![image](https://user-images.githubusercontent.com/2487306/108872602-56aad780-7620-11eb-81ee-8ea04ac4bb4c.png)

**Comment by vipul-sharma20** [comment]
Using: https://github.com/rouge-ruby/rouge

monokai sublime ->

![image](https://i.imgur.com/rslJs4e.png)

**Comment by lepisma** [comment]
can we use a light theme? dark blocks looks weird in light pages imo (unless the boundaries are polished well)
