### ISSUE TITLE
latex extension problem

### ISSUE THREAD

**Issue by swarajdalmia** [Vernacular-ai/tech#50]
The current latex extension can't currently handle inline product i.e \prod. I tried a bunch of different things but nothing worked. Maybe there are some other limitations for inline teX capabilities.

**Comment by lepisma** [comment]
works for me, see screenshot

![image](https://user-images.githubusercontent.com/2487306/117582012-9fe9ce00-b11d-11eb-9aa8-0d3665fc3094.png)

**Comment by swarajdalmia** [comment]
I think the issue is when the product has a sub-script and a superscript.

**Comment by lepisma** [comment]
![image](https://user-images.githubusercontent.com/2487306/118391862-12920680-b654-11eb-8b75-768f76dd56c6.png)

this also works. `Hello $$ \prod_{i = 1}^{100} $$ world`

**Comment by greed2411** [comment]
closing this issue, but please feel to reopen if latex issue persists.
